### ISSUE TITLE
VariableEntity displays shortGuid instead of name

### ISSUE THREAD

**Issue by Oliver2Goetz** [MattFiler/OpenCAGE#124]
I created the following Variable Entity:
![image](https://user-images.githubusercontent.com/44117499/211124095-455ec766-6a55-4ba5-a50d-f1cd5d2b5b1f.png)

The name itself doesn't show up as the name. Instead the shortGuid is shown as name:
![image](https://user-images.githubusercontent.com/44117499/211124145-cad291af-a0eb-4b5f-85de-58d4136139bb.png)
The parameter also gets the shortGuid displayed.

Earlier I updated my PAKDifferentiation repository to use CathodeLib0.3 instead of 0.2. There I discovered that the `ToString()` method got changed and a `ToByteString()` method was added in the following file:
`CathodeLib/Scripts/CATHODE/CommandsPAK/Components/ShortGuid.cs`

I assume that's the case for the problem here as well and the `ToString()` has to be switched to `ToByteString()`.

**Comment by MattFiler** [comment]
This is due to the `ShortGuidUtils` not saving custom `ShortGuid` values out to the COMMANDS.PAK, like how custom entity names are saved through `EntityUtils` currently. If you enter a string which already exists within the scripting system it'll work.

I'll be adding support for custom string saving very soon :)

**Comment by MattFiler** [comment]
Just pushed an update to the staging branch which allows the ability to save custom variable names. Please be aware that this is a breaking change, and all previously saved entity names will be unrecoverable.
