### ISSUE TITLE
enhancement: character generator should direct to NPC composite ; disallow selection of wrong 'parts'.

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#213]
Just mucking with the character generator.  Two things.   
One must manually scroll down and open the NPC hierarchy for each component part and then not 
mistakenly add wrong part on each line.  Is there anyway to make sure that each part is correct 
for the given field?  We don't want torso in place of arms. ( Well not unless we're Dr. Nick Riveria from The Simpons :P )
I made a mis-click and did such a mistake:
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/e267200f-be7b-45dc-abad-fd8cb3ef0df6)

Not sure the game would take kindly to such things either.  Some sort of sanity check to be sure the created model
is within whatever the game expects?

**Comment by MattFiler** [comment]
Selecting the root `Character` is something that I'm planning on making better in future updates, definitely!

In terms of selecting the correct body parts, I intentionally left it open ended so that if in future you added custom composites you wouldn't be restricted by the ones named in the base game. There's no easy way to tag composites for a purpose without me manually going through all the ones in the base game and tagging them with the same tagging system I'd have to implement - but I'll leave this issue open to cover that if it arises.

**Comment by ghramsey** [comment]
Got it.  Yeah.  I know it's a tall order.  Selecting only character seems to make sense.
We gonna have some odd looking dudes and dudettes (!) if any of those torso for an arm assetts get mixed up. 
I don't think it will happen often, but as I originally made just such a mistake through mis-click it's possible to happen.
Just hope it's not something that will break anything too much and will be un-doable.

**Comment by MattFiler** [comment]
I'm gonna close this as I think it's unresolvable without manually tagging all composites for their intended use, which is something I don't plan on implementing (any time soon at least).
