### ISSUE TITLE
enhancement: edit entity type 

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#234]
It might not be practical in all instances, but can we have the ablity to edit entity types?
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/08a3299b-b56d-4425-91a2-9286bf01f1cc)

In this instance I created a float variable, but I need a position marker.
To fix this I have to delete the entity and recreated it and all it's links.  
The ablity to change just it's type would be most helpful.

**Comment by MattFiler** [comment]
While I get the request, I'm gonna close this one as "won't do". There are significant overheads with changing entity type as it affects all the connected resources and parameters. In most cases you wouldn't want the same parameters and links to be transferred between entity types due to their different natures.
