### ISSUE TITLE
Script Editor UX Tweaks

### ISSUE THREAD

**Issue by MattFiler** [MattFiler/OpenCAGE#267]
After playing around with the script editor, a few UX suggestions:
- [x] Add support for making composite folders
- [ ] Select entity/composite in the correct lists when they are loaded
- [x] Add support for searching composite tree
- [x] Add button to find uses of FunctionEntity types
- [x] Add option to disable opening new tabs for composites/entities
- [x] Add context menu for composite actions, including deleting whole folders
- [x] Add context menu for entity actions
- [ ] Change the "function" button text to make sense to the entity
- [x] Rename the root composite to just be the level name, and/or separate the root and PAUSEMENU and GLOBAL composites out
- [x] Add copy/paste function for transforms

**Comment by Const1702** [comment]
Just noticed that the composite folder creation window is maximizable:
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/79955bc1-5493-4d1a-a7e7-371039701760)
![image](https://github.com/MattFiler/OpenCAGE/assets/116276106/18a9a5e8-3af4-4da3-838f-599df5b2568b)

**OpenCAGE version: 0.11.1.02 (Staging)**

**Comment by MattFiler** [comment]
Cheers @Const1702 - fixed in latest staging.

**Comment by Const1702** [comment]
Noticed an update to the way composites (prefabs) are displayed in the entity list, where they don't show their full path as their name, which is a really nice improvement, because they were really clogging up the list. Let's say, however, that I want to search for all science related corridor elements. I can go to all floor, wall, ceiling entities and find their instanceswith the uses window, but that would lead me to closing the opened composite and going back to it over and over for each science-related composite I check. What I could do before was type in the search box 'AYZ\SCIENCE\CORRIDOR_ELEMENTS' and it would show me all composite entities that start with that path. The request is to **keep the composite names simple in lists**, but to **be able to search for their full paths**. If that starts to get in the way you can add  an option in the "Options" toolstrip dropdown "Search only for composite names in lists (without paths)".

Replying here, because this is related to UI and I'm very unsure, if it is possible to implement. Let me know, if you want me to post it as a seperate issue.

**Comment by ghramsey** [comment]
I'm going to post this under this ticket since I think it's part of the changes.

The new UI includes:
Composite display is now pinned to bottom, and auto hides to increase display space (this can be undone by clicking the pin)

Can u make it so this setting state is saved?  It auto unpins when a new map is loaded.
