### ISSUE TITLE
LOD values

### ISSUE THREAD

**Issue by d0x360** [MattFiler/OpenCAGE#30]
I just did a clean install of win10 and alien and by sheet luck found this cool tool.

Anyways my issue... In the graphics settings I lower the LOD value because I thought lower LOD would work like the nVidia cp used to and force it to always use high quality models.

It didn't work so then I set it to 1 and it was the same.  I'm probably doing something wrong but I don't know what.

**Comment by MattFiler** [comment]
Level of detail "pop-in" distance is scaled by the LOD value option selected. You can change this LOD value by editing the presets in the graphics settings editor.

By default, the LOD value scalar is in the range of 1.0-0.6 (1.0 being "Ultra", and 0.6 being "Low"). Because this is simply a scalar, you can add a custom LOD value preset of a giant number, and you'll no longer have lower LODs load in (E.G. I have mine set on 10,000).

Hope this helps!

**Comment by d0x360** [comment]
I added the number 6 and I was still getting obvious pop in

**Comment by d0x360** [comment]
I will try 10,000.  I don't know how I missed that part of your post, my apologies.
