### ISSUE TITLE
OpenCAGE changelog

### ISSUE THREAD

**Issue by ICDeadPpl** [MattFiler/OpenCAGE#300]
What's the deal with a changelog 579 lines long, with listed changes going back to 7th March 2022?
Each release should have the changes relevant to that version/tag only?
<a href='https://github.com/MattFiler/OpenCAGE/releases/tag/0.11.2.2'>OpenCAGE v0.11.2.2 changelog</a>

**Comment by MattFiler** [comment]
OpenCAGE auto updates, so I always remove the old release tags from GitHub because otherwise if you downloaded an old build it'd just auto update to the latest release. Doing that though means I lose the changelogs if I don't copy them through to the next one. Will go through and prune them at some point (maybe move them to opencage.co.uk) 👍

**Comment by MattFiler** [comment]
Forgot to update this ticket - but I do now store full changelogs outside of GitHub to reduce their length. You can find the full thing here: https://opencage.co.uk/docs/changelog/
