### ISSUE TITLE
Direct edit to commands.pak changes root node to show P:\

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#307]
I'm not certain how to properly describe the issue.   I don't think this is anything critical.  I believe it's only visual.
When direct editing the commands.pak using visual studio and your "example code" here: https://github.com/OpenCAGE/CathodeLib/wiki/Creating-your-first-Cathode-script

 the root node reverts to the P:\ tree visually vs the changes that have been recently made:
 
![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/a6a29ecc-9bf6-416d-98cc-c4a6a10500ff)

Oh.  To be clear. This was a stock vanilla commands.pak file. 
In fact, I just verified the game files before editing and made a backup using the back up manager.
I'm just mucking around too hence using the example code.

**Comment by MattFiler** [comment]
This'll be because you've set "My Cool Script" to be the root composite (the one the level loads to). It's probably best practice to add a composite and then instance it within the existing root composite (the one that has the full filepath).

To add a composite and not set it as the root, remove the `true` parameter from the `AddComposite` function.

**Comment by ghramsey** [comment]
OK.  So that is expected behavior for that script.  Thank you.
