### ISSUE TITLE
Cathode Editor level dropdown greys-out during loading and remains grey

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#56]
The drop down list of level names greys out following loading.    The load button greys out while loading and does not become active.
![image](https://user-images.githubusercontent.com/51859157/158045164-f92a72da-005f-40bc-bd4f-6c3ee63bf61b.png)

I think it's supposed to be greyed while loading the file but it's inconsistent that it reenables.
Or it's taking long to load but there is nothing to indicate which one.

This is on the new update just pushed at launched of the program.  0.9.0.2 Master

**Comment by MattFiler** [comment]
This is expected behaviour - when you load a level the tool caches entity names in the background. When caching has finished, the dropdown and load button should be active again.

How long did you wait for the buttons to become re-enabled? It should usually take about 1-2 mins, but obviously varies depending on the size of the level's scripts.

**Comment by ghramsey** [comment]
OK. That explains why it seemed to be delayed.   I did let it load for a while and it did seem to clear out.

Still as a suggestion might want an icon to indicate it's loading.   How about white text on the grey background "loading".
Mainly since this didn't happen on the previous versions.

**Comment by MattFiler** [comment]
The UX of the tool isn't the best right now, as once I've fully figured out the COMMANDS format I'm hoping to move across to a node-based interface - but yeah nice suggestion, I'll get a loading icon added for the next release.

**Comment by MattFiler** [comment]
Implemented this in today's release (0.9.2.2)
