### ISSUE TITLE
Enhancement - dropdown list cut off on right side add window scroll

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#82]
![image](https://user-images.githubusercontent.com/51859157/202299021-ac51cd2e-7dbf-44d6-ac75-42b1c427f054.png)
Any chance you can add a scroll sideways option or widen the dropdown list box? 
It's cut off for most of the super-long entitiy names + paths such as this one.

**Comment by ghramsey** [comment]
Probably related to this same issue. The position fields are too narrow by one digit.  Can you widen them a hair so all the 
0s appear.  In this box my mouse is pointing to there is a negative sign that is cut off by the box width.
![image](https://user-images.githubusercontent.com/51859157/203582096-dbf756c4-400a-44ce-9806-f1c136a946a7.png)

**Comment by MattFiler** [comment]
If you swap to the `staging` branch via OpenCAGE's settings, this has now been tweaked - entity info stretches across that full UI, and flows downwards instead of across.

Please note the `staging` branch also contains various other changes to the scripting tool in regards to resources, and may not be as stable as the `main` branch.

**Comment by ghramsey** [comment]
Cool. That's what I just grabbed. 0.9.3.02 staging.
I have been using the staging branch almost exclusively.
